/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_persons_line_token1 = 1,
  anon_sym_Personen = 2,
  anon_sym_Portionen = 3,
  anon_sym_POUND_POUNDZutaten = 4,
  anon_sym_POUND_POUNDZubereitung = 5,
  anon_sym_DASH = 6,
  sym_integer = 7,
  sym_float = 8,
  sym_unit = 9,
  sym_text = 10,
  sym_ingredient_name = 11,
  sym_preamble_line = 12,
  sym_source_file = 13,
  sym_persons_line = 14,
  sym_ingredients_section = 15,
  sym_preparation_section = 16,
  sym_ingredient_line = 17,
  sym_quantity = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym_ingredients_section_repeat1 = 20,
  aux_sym_preparation_section_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_persons_line_token1] = "persons_line_token1",
  [anon_sym_Personen] = "Personen",
  [anon_sym_Portionen] = "Portionen",
  [anon_sym_POUND_POUNDZutaten] = "## Zutaten",
  [anon_sym_POUND_POUNDZubereitung] = "## Zubereitung",
  [anon_sym_DASH] = "-",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_unit] = "unit",
  [sym_text] = "text",
  [sym_ingredient_name] = "ingredient_name",
  [sym_preamble_line] = "preamble_line",
  [sym_source_file] = "source_file",
  [sym_persons_line] = "persons_line",
  [sym_ingredients_section] = "ingredients_section",
  [sym_preparation_section] = "preparation_section",
  [sym_ingredient_line] = "ingredient_line",
  [sym_quantity] = "quantity",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_ingredients_section_repeat1] = "ingredients_section_repeat1",
  [aux_sym_preparation_section_repeat1] = "preparation_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_persons_line_token1] = aux_sym_persons_line_token1,
  [anon_sym_Personen] = anon_sym_Personen,
  [anon_sym_Portionen] = anon_sym_Portionen,
  [anon_sym_POUND_POUNDZutaten] = anon_sym_POUND_POUNDZutaten,
  [anon_sym_POUND_POUNDZubereitung] = anon_sym_POUND_POUNDZubereitung,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_unit] = sym_unit,
  [sym_text] = sym_text,
  [sym_ingredient_name] = sym_ingredient_name,
  [sym_preamble_line] = sym_preamble_line,
  [sym_source_file] = sym_source_file,
  [sym_persons_line] = sym_persons_line,
  [sym_ingredients_section] = sym_ingredients_section,
  [sym_preparation_section] = sym_preparation_section,
  [sym_ingredient_line] = sym_ingredient_line,
  [sym_quantity] = sym_quantity,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_ingredients_section_repeat1] = aux_sym_ingredients_section_repeat1,
  [aux_sym_preparation_section_repeat1] = aux_sym_preparation_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_persons_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Personen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Portionen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDZutaten] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUNDZubereitung] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient_name] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_persons_line] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredients_section] = {
    .visible = true,
    .named = true,
  },
  [sym_preparation_section] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient_line] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ingredients_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preparation_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_name = 2,
  field_quantity = 3,
  field_unit = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_name] = "name",
  [field_quantity] = "quantity",
  [field_unit] = "unit",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_count, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 2},
    {field_quantity, 1},
  [4] =
    {field_name, 3},
    {field_quantity, 1},
    {field_unit, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(106);
      ADVANCE_MAP(
        '#', 10,
        '-', 114,
        'B', 94,
        'D', 71,
        'E', 16,
        'G', 125,
        'K', 15,
        'L', 123,
        'M', 35,
        'P', 20,
        'S', 27,
        'T', 16,
        'e', 60,
        'g', 125,
        'k', 46,
        'l', 120,
        'm', 101,
        's', 30,
        't', 60,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(215);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '-') ADVANCE(114);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(215);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == 'B') ADVANCE(182);
      if (lookahead == 'D') ADVANCE(169);
      if (lookahead == 'E') ADVANCE(134);
      if (lookahead == 'G') ADVANCE(126);
      if (lookahead == 'K') ADVANCE(133);
      if (lookahead == 'L') ADVANCE(124);
      if (lookahead == 'M') ADVANCE(149);
      if (lookahead == 'P') ADVANCE(135);
      if (lookahead == 'S') ADVANCE(139);
      if (lookahead == 'T') ADVANCE(134);
      if (lookahead == 'e') ADVANCE(164);
      if (lookahead == 'g') ADVANCE(126);
      if (lookahead == 'k') ADVANCE(153);
      if (lookahead == 'l') ADVANCE(120);
      if (lookahead == 'm') ADVANCE(187);
      if (lookahead == 's') ADVANCE(142);
      if (lookahead == 't') ADVANCE(164);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(107);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(120);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(120);
      if (lookahead == 'i') ADVANCE(86);
      END_STATE();
    case 15:
      if (lookahead == 'G') ADVANCE(120);
      END_STATE();
    case 16:
      if (lookahead == 'L') ADVANCE(120);
      END_STATE();
    case 17:
      if (lookahead == 'Z') ADVANCE(95);
      END_STATE();
    case 18:
      if (lookahead == 'Z') ADVANCE(98);
      END_STATE();
    case 19:
      if (lookahead == 'Z') ADVANCE(97);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 'k') ADVANCE(47);
      if (lookahead == 'o') ADVANCE(77);
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(81);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'b') ADVANCE(41);
      END_STATE();
    case 25:
      if (lookahead == 'b') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'b') ADVANCE(40);
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(59);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(120);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(87);
      if (lookahead == 's') ADVANCE(74);
      if (lookahead == 'G' ||
          lookahead == 'L') ADVANCE(120);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 46:
      if (lookahead == 'g') ADVANCE(120);
      END_STATE();
    case 47:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 48:
      if (lookahead == 'g') ADVANCE(122);
      END_STATE();
    case 49:
      if (lookahead == 'g') ADVANCE(112);
      END_STATE();
    case 50:
      if (lookahead == 'h') ADVANCE(36);
      END_STATE();
    case 51:
      if (lookahead == 'h') ADVANCE(38);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(93);
      END_STATE();
    case 56:
      if (lookahead == 'i') ADVANCE(34);
      if (lookahead == 'k') ADVANCE(120);
      if (lookahead == 0xfc) ADVANCE(28);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 58:
      if (lookahead == 'k') ADVANCE(120);
      END_STATE();
    case 59:
      if (lookahead == 'k') ADVANCE(96);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(120);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(109);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(110);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 70:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(82);
      END_STATE();
    case 72:
      if (lookahead == 'o') ADVANCE(69);
      END_STATE();
    case 73:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(120);
      END_STATE();
    case 75:
      if (lookahead == 'p') ADVANCE(54);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(120);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(83);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 81:
      if (lookahead == 's') ADVANCE(120);
      END_STATE();
    case 82:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 83:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 84:
      if (lookahead == 's') ADVANCE(75);
      END_STATE();
    case 85:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 86:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(85);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 94:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 95:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 96:
      if (lookahead == 'u') ADVANCE(67);
      END_STATE();
    case 97:
      if (lookahead == 'u') ADVANCE(90);
      END_STATE();
    case 98:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 99:
      if (lookahead == 'u') ADVANCE(68);
      END_STATE();
    case 100:
      if (lookahead == 'z') ADVANCE(32);
      END_STATE();
    case 101:
      if (lookahead == 'g' ||
          lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 102:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(102);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 103:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 104:
      if (eof) ADVANCE(106);
      if (lookahead == '\n') SKIP(104);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '-') ADVANCE(114);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 105:
      if (eof) ADVANCE(106);
      if (lookahead == '\n') SKIP(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(129);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_persons_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_Personen);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_Portionen);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDZutaten);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDZutaten);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDZubereitung);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_POUND_POUNDZubereitung);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(188);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_unit);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'e') ADVANCE(166);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'i') ADVANCE(181);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'l') ADVANCE(136);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_unit);
      if (lookahead == 'n') ADVANCE(120);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(129);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == '.') ADVANCE(120);
      if (lookahead == 'i') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-' &&
          lookahead != '.') ADVANCE(189);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == '.') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-' &&
          lookahead != '.') ADVANCE(189);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_ingredient_name);
      ADVANCE_MAP(
        'B', 182,
        'D', 169,
        'E', 134,
        'G', 126,
        'K', 133,
        'L', 124,
        'M', 149,
        'P', 135,
        'S', 139,
        'T', 134,
        'e', 164,
        'g', 126,
        'k', 153,
        'l', 120,
        'm', 187,
        's', 142,
        't', 164,
        '\t', 132,
        ' ', 132,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'G') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'L') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'a') ADVANCE(141);
      if (lookahead == 'k') ADVANCE(154);
      if (lookahead == 'r') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'a') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'b') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'b') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'c') ADVANCE(156);
      if (lookahead == 't') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'c') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'c') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'c') ADVANCE(157);
      if (lookahead == 't') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'd') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(179);
      if (lookahead == 's') ADVANCE(170);
      if (lookahead == 'G' ||
          lookahead == 'L') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'e') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'g') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'g') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'g') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'h') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'h') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'i') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'i') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'i') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'i') ADVANCE(148);
      if (lookahead == 'k') ADVANCE(120);
      if (lookahead == 0xfc) ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'k') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'k') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'l') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'l') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'n') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'n') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'n') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'o') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'p') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'p') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'r') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'r') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 's') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 's') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 's') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 's') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 's') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 's') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 't') ADVANCE(184);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 't') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'u') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'u') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'z') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead == 'g' ||
          lookahead == 'l') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_ingredient_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(189);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == ' ') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == ' ') ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == '#') ADVANCE(215);
      if (lookahead == '-') ADVANCE(115);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == '#') ADVANCE(194);
      if (lookahead == '-') ADVANCE(115);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == '#') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == '#') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == '#') ADVANCE(195);
      if (lookahead == '-') ADVANCE(215);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'Z') ADVANCE(212);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'Z') ADVANCE(214);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'a') ADVANCE(211);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'b') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'e') ADVANCE(208);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'e') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'e') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'g') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'i') ADVANCE(210);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'n') ADVANCE(204);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'n') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'r') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 't') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 't') ADVANCE(213);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 't') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'u') ADVANCE(200);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'u') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead == 'u') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_preamble_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(215);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 102},
  [2] = {.lex_state = 104},
  [3] = {.lex_state = 104},
  [4] = {.lex_state = 104},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 104},
  [10] = {.lex_state = 104},
  [11] = {.lex_state = 104},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 105},
  [15] = {.lex_state = 105},
  [16] = {.lex_state = 105},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Personen] = ACTIONS(1),
    [anon_sym_Portionen] = ACTIONS(1),
    [anon_sym_POUND_POUNDZutaten] = ACTIONS(1),
    [anon_sym_POUND_POUNDZubereitung] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_unit] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_persons_line] = STATE(5),
    [sym_integer] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      anon_sym_POUND_POUNDZubereitung,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      sym_preamble_line,
    STATE(3), 2,
      sym_ingredient_line,
      aux_sym_ingredients_section_repeat1,
  [17] = 5,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_POUND_POUNDZubereitung,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(20), 1,
      sym_preamble_line,
    STATE(3), 2,
      sym_ingredient_line,
      aux_sym_ingredients_section_repeat1,
  [34] = 2,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 3,
      anon_sym_POUND_POUNDZubereitung,
      anon_sym_DASH,
      sym_preamble_line,
  [43] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND_POUNDZutaten,
    ACTIONS(29), 1,
      sym_preamble_line,
    STATE(8), 1,
      aux_sym_source_file_repeat1,
    STATE(12), 1,
      sym_ingredients_section,
  [56] = 3,
    ACTIONS(33), 1,
      sym_ingredient_name,
    STATE(20), 1,
      sym_quantity,
    ACTIONS(31), 2,
      sym_integer,
      sym_float,
  [67] = 3,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      sym_preamble_line,
    STATE(2), 2,
      sym_ingredient_line,
      aux_sym_ingredients_section_repeat1,
  [78] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND_POUNDZutaten,
    ACTIONS(35), 1,
      sym_preamble_line,
    STATE(13), 1,
      sym_ingredients_section,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
  [91] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 3,
      anon_sym_POUND_POUNDZubereitung,
      anon_sym_DASH,
      sym_preamble_line,
  [100] = 2,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 3,
      anon_sym_POUND_POUNDZubereitung,
      anon_sym_DASH,
      sym_preamble_line,
  [109] = 2,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 3,
      anon_sym_POUND_POUNDZubereitung,
      anon_sym_DASH,
      sym_preamble_line,
  [118] = 3,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_POUND_POUNDZubereitung,
    STATE(25), 1,
      sym_preparation_section,
  [128] = 3,
    ACTIONS(51), 1,
      anon_sym_POUND_POUNDZubereitung,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_preparation_section,
  [138] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      sym_text,
    STATE(15), 1,
      aux_sym_preparation_section_repeat1,
  [148] = 3,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym_text,
    STATE(16), 1,
      aux_sym_preparation_section_repeat1,
  [158] = 3,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      sym_text,
    STATE(16), 1,
      aux_sym_preparation_section_repeat1,
  [168] = 3,
    ACTIONS(68), 1,
      anon_sym_POUND_POUNDZutaten,
    ACTIONS(70), 1,
      sym_preamble_line,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
  [178] = 1,
    ACTIONS(73), 2,
      anon_sym_POUND_POUNDZutaten,
      sym_preamble_line,
  [183] = 1,
    ACTIONS(75), 2,
      anon_sym_Personen,
      anon_sym_Portionen,
  [188] = 2,
    ACTIONS(77), 1,
      sym_unit,
    ACTIONS(79), 1,
      sym_ingredient_name,
  [195] = 1,
    ACTIONS(81), 2,
      sym_unit,
      sym_ingredient_name,
  [200] = 1,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [204] = 1,
    ACTIONS(85), 1,
      aux_sym_persons_line_token1,
  [208] = 1,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
  [212] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [216] = 1,
    ACTIONS(89), 1,
      sym_ingredient_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 43,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 67,
  [SMALL_STATE(8)] = 78,
  [SMALL_STATE(9)] = 91,
  [SMALL_STATE(10)] = 100,
  [SMALL_STATE(11)] = 109,
  [SMALL_STATE(12)] = 118,
  [SMALL_STATE(13)] = 128,
  [SMALL_STATE(14)] = 138,
  [SMALL_STATE(15)] = 148,
  [SMALL_STATE(16)] = 158,
  [SMALL_STATE(17)] = 168,
  [SMALL_STATE(18)] = 178,
  [SMALL_STATE(19)] = 183,
  [SMALL_STATE(20)] = 188,
  [SMALL_STATE(21)] = 195,
  [SMALL_STATE(22)] = 200,
  [SMALL_STATE(23)] = 204,
  [SMALL_STATE(24)] = 208,
  [SMALL_STATE(25)] = 212,
  [SMALL_STATE(26)] = 216,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredients_section, 2, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ingredients_section, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ingredients_section_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ingredients_section_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ingredients_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ingredients_section_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_line, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ingredient_line, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_line, 3, 0, 3),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ingredient_line, 3, 0, 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_line, 2, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ingredient_line, 2, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient_line, 4, 0, 4),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ingredient_line, 4, 0, 4),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preparation_section, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preparation_section, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preparation_section_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preparation_section_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_persons_line, 3, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quantity, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dish(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dish",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
