/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__line_break = 1,
  anon_sym_Personen_COLON = 2,
  anon_sym_Starttag_COLON = 3,
  sym_integer = 4,
  sym_date = 5,
  anon_sym_COLON = 6,
  sym_day_name = 7,
  sym_count = 8,
  sym_rest_day = 9,
  anon_sym_COMMA = 10,
  anon_sym_u27e8 = 11,
  aux_sym_shopping_marker_token1 = 12,
  anon_sym_u27e9 = 13,
  anon_sym_LBRACK_LBRACK = 14,
  aux_sym_dish_token1 = 15,
  anon_sym_RBRACK_RBRACK = 16,
  sym_source_file = 17,
  sym_persons_line = 18,
  sym_starttag_line = 19,
  sym_day_line = 20,
  sym_day_with_count = 21,
  sym_menu = 22,
  sym_menu_items = 23,
  sym_menu_item = 24,
  sym_shopping_marker = 25,
  sym_dish_with_count = 26,
  sym_dish = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_menu_items_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__line_break] = "_line_break",
  [anon_sym_Personen_COLON] = "Personen:",
  [anon_sym_Starttag_COLON] = "Starttag:",
  [sym_integer] = "integer",
  [sym_date] = "date",
  [anon_sym_COLON] = ":",
  [sym_day_name] = "day_name",
  [sym_count] = "count",
  [sym_rest_day] = "rest_day",
  [anon_sym_COMMA] = ",",
  [anon_sym_u27e8] = "\u27e8",
  [aux_sym_shopping_marker_token1] = "shopping_marker_token1",
  [anon_sym_u27e9] = "\u27e9",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [aux_sym_dish_token1] = "dish_token1",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_source_file] = "source_file",
  [sym_persons_line] = "persons_line",
  [sym_starttag_line] = "starttag_line",
  [sym_day_line] = "day_line",
  [sym_day_with_count] = "day_with_count",
  [sym_menu] = "menu",
  [sym_menu_items] = "menu_items",
  [sym_menu_item] = "menu_item",
  [sym_shopping_marker] = "shopping_marker",
  [sym_dish_with_count] = "dish_with_count",
  [sym_dish] = "dish",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_menu_items_repeat1] = "menu_items_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__line_break] = sym__line_break,
  [anon_sym_Personen_COLON] = anon_sym_Personen_COLON,
  [anon_sym_Starttag_COLON] = anon_sym_Starttag_COLON,
  [sym_integer] = sym_integer,
  [sym_date] = sym_date,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_day_name] = sym_day_name,
  [sym_count] = sym_count,
  [sym_rest_day] = sym_rest_day,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_u27e8] = anon_sym_u27e8,
  [aux_sym_shopping_marker_token1] = aux_sym_shopping_marker_token1,
  [anon_sym_u27e9] = anon_sym_u27e9,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [aux_sym_dish_token1] = aux_sym_dish_token1,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_persons_line] = sym_persons_line,
  [sym_starttag_line] = sym_starttag_line,
  [sym_day_line] = sym_day_line,
  [sym_day_with_count] = sym_day_with_count,
  [sym_menu] = sym_menu,
  [sym_menu_items] = sym_menu_items,
  [sym_menu_item] = sym_menu_item,
  [sym_shopping_marker] = sym_shopping_marker,
  [sym_dish_with_count] = sym_dish_with_count,
  [sym_dish] = sym_dish,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_menu_items_repeat1] = aux_sym_menu_items_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__line_break] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Personen_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Starttag_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_day_name] = {
    .visible = true,
    .named = true,
  },
  [sym_count] = {
    .visible = true,
    .named = true,
  },
  [sym_rest_day] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u27e8] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_shopping_marker_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u27e9] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dish_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_persons_line] = {
    .visible = true,
    .named = true,
  },
  [sym_starttag_line] = {
    .visible = true,
    .named = true,
  },
  [sym_day_line] = {
    .visible = true,
    .named = true,
  },
  [sym_day_with_count] = {
    .visible = true,
    .named = true,
  },
  [sym_menu] = {
    .visible = true,
    .named = true,
  },
  [sym_menu_items] = {
    .visible = true,
    .named = true,
  },
  [sym_menu_item] = {
    .visible = true,
    .named = true,
  },
  [sym_shopping_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_dish_with_count] = {
    .visible = true,
    .named = true,
  },
  [sym_dish] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_menu_items_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_date = 2,
  field_day = 3,
  field_dish = 4,
  field_name = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_date] = "date",
  [field_day] = "day",
  [field_dish] = "dish",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_count, 1},
  [1] =
    {field_date, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_count, 1},
    {field_name, 0},
  [5] =
    {field_day, 0},
  [6] =
    {field_dish, 0},
  [7] =
    {field_count, 1},
    {field_dish, 0},
  [9] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '\n', 41,
        '(', 31,
        ',', 55,
        ':', 50,
        'P', 11,
        'R', 12,
        'S', 23,
        '[', 7,
        ']', 8,
        0x27e8, 56,
        0x27e9, 59,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(43);
      END_STATE();
    case 7:
      if (lookahead == '[') ADVANCE(60);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(6);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a &&
          lookahead != 0x27e9) ADVANCE(58);
      END_STATE();
    case 28:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(62);
      END_STATE();
    case 29:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(2);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__line_break);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_Personen_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_Starttag_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '-') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_day_name);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_day_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '(' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_count);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_rest_day);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_u27e8);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_shopping_marker_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a &&
          lookahead != 0x27e9) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_shopping_marker_token1);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a &&
          lookahead != 0x27e9) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_u27e9);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_dish_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_dish_token1);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 39},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 27},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 29},
  [40] = {.lex_state = 30},
  [41] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__line_break] = ACTIONS(1),
    [anon_sym_Personen_COLON] = ACTIONS(1),
    [anon_sym_Starttag_COLON] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_count] = ACTIONS(1),
    [sym_rest_day] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_u27e8] = ACTIONS(1),
    [anon_sym_u27e9] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym_persons_line] = STATE(36),
    [sym__line_break] = ACTIONS(3),
    [anon_sym_Personen_COLON] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      sym_rest_day,
    ACTIONS(11), 1,
      anon_sym_u27e8,
    ACTIONS(13), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(3), 1,
      sym_menu_item,
    STATE(7), 1,
      sym_dish,
    STATE(27), 1,
      sym_menu,
    STATE(29), 1,
      sym_menu_items,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      sym__line_break,
    STATE(10), 2,
      sym_shopping_marker,
      sym_dish_with_count,
  [30] = 7,
    ACTIONS(11), 1,
      anon_sym_u27e8,
    ACTIONS(13), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(17), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      sym_dish,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      sym__line_break,
    STATE(4), 2,
      sym_menu_item,
      aux_sym_menu_items_repeat1,
    STATE(10), 2,
      sym_shopping_marker,
      sym_dish_with_count,
  [55] = 7,
    ACTIONS(11), 1,
      anon_sym_u27e8,
    ACTIONS(13), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(17), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      sym_dish,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym__line_break,
    STATE(5), 2,
      sym_menu_item,
      aux_sym_menu_items_repeat1,
    STATE(10), 2,
      sym_shopping_marker,
      sym_dish_with_count,
  [80] = 7,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(26), 1,
      anon_sym_u27e8,
    ACTIONS(29), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(7), 1,
      sym_dish,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      sym__line_break,
    STATE(5), 2,
      sym_menu_item,
      aux_sym_menu_items_repeat1,
    STATE(10), 2,
      sym_shopping_marker,
      sym_dish_with_count,
  [105] = 5,
    ACTIONS(11), 1,
      anon_sym_u27e8,
    ACTIONS(13), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(7), 1,
      sym_dish,
    STATE(12), 1,
      sym_menu_item,
    STATE(10), 2,
      sym_shopping_marker,
      sym_dish_with_count,
  [122] = 2,
    ACTIONS(34), 1,
      sym_count,
    ACTIONS(32), 5,
      ts_builtin_sym_end,
      sym__line_break,
      anon_sym_COMMA,
      anon_sym_u27e8,
      anon_sym_LBRACK_LBRACK,
  [133] = 1,
    ACTIONS(36), 6,
      ts_builtin_sym_end,
      sym__line_break,
      sym_count,
      anon_sym_COMMA,
      anon_sym_u27e8,
      anon_sym_LBRACK_LBRACK,
  [142] = 1,
    ACTIONS(38), 5,
      ts_builtin_sym_end,
      sym__line_break,
      anon_sym_COMMA,
      anon_sym_u27e8,
      anon_sym_LBRACK_LBRACK,
  [150] = 1,
    ACTIONS(40), 5,
      ts_builtin_sym_end,
      sym__line_break,
      anon_sym_COMMA,
      anon_sym_u27e8,
      anon_sym_LBRACK_LBRACK,
  [158] = 1,
    ACTIONS(42), 5,
      ts_builtin_sym_end,
      sym__line_break,
      anon_sym_COMMA,
      anon_sym_u27e8,
      anon_sym_LBRACK_LBRACK,
  [166] = 1,
    ACTIONS(21), 5,
      ts_builtin_sym_end,
      sym__line_break,
      anon_sym_COMMA,
      anon_sym_u27e8,
      anon_sym_LBRACK_LBRACK,
  [174] = 4,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      sym_day_name,
    STATE(26), 1,
      sym_day_line,
    STATE(31), 1,
      sym_day_with_count,
  [187] = 4,
    ACTIONS(46), 1,
      sym_day_name,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym_day_line,
    STATE(31), 1,
      sym_day_with_count,
  [200] = 4,
    ACTIONS(46), 1,
      sym_day_name,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym_day_line,
    STATE(31), 1,
      sym_day_with_count,
  [213] = 3,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym__line_break,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
  [223] = 3,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym__line_break,
    STATE(21), 1,
      aux_sym_source_file_repeat1,
  [233] = 3,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym__line_break,
    STATE(21), 1,
      aux_sym_source_file_repeat1,
  [243] = 3,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      sym__line_break,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
  [253] = 3,
    ACTIONS(46), 1,
      sym_day_name,
    STATE(26), 1,
      sym_day_line,
    STATE(31), 1,
      sym_day_with_count,
  [263] = 3,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      sym__line_break,
    STATE(21), 1,
      aux_sym_source_file_repeat1,
  [273] = 2,
    ACTIONS(65), 1,
      anon_sym_Starttag_COLON,
    STATE(19), 1,
      sym_starttag_line,
  [280] = 2,
    ACTIONS(65), 1,
      anon_sym_Starttag_COLON,
    STATE(16), 1,
      sym_starttag_line,
  [287] = 1,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym__line_break,
  [292] = 2,
    ACTIONS(69), 1,
      anon_sym_COLON,
    ACTIONS(71), 1,
      sym_count,
  [299] = 1,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      sym__line_break,
  [304] = 1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym__line_break,
  [309] = 2,
    ACTIONS(5), 1,
      anon_sym_Personen_COLON,
    STATE(41), 1,
      sym_persons_line,
  [316] = 1,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym__line_break,
  [321] = 1,
    ACTIONS(77), 1,
      anon_sym_COLON,
  [325] = 1,
    ACTIONS(79), 1,
      anon_sym_COLON,
  [329] = 1,
    ACTIONS(81), 1,
      sym__line_break,
  [333] = 1,
    ACTIONS(83), 1,
      anon_sym_u27e9,
  [337] = 1,
    ACTIONS(85), 1,
      anon_sym_RBRACK_RBRACK,
  [341] = 1,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
  [345] = 1,
    ACTIONS(89), 1,
      sym__line_break,
  [349] = 1,
    ACTIONS(91), 1,
      aux_sym_shopping_marker_token1,
  [353] = 1,
    ACTIONS(93), 1,
      aux_sym_dish_token1,
  [357] = 1,
    ACTIONS(95), 1,
      sym_date,
  [361] = 1,
    ACTIONS(97), 1,
      sym_integer,
  [365] = 1,
    ACTIONS(99), 1,
      sym__line_break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 55,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 105,
  [SMALL_STATE(7)] = 122,
  [SMALL_STATE(8)] = 133,
  [SMALL_STATE(9)] = 142,
  [SMALL_STATE(10)] = 150,
  [SMALL_STATE(11)] = 158,
  [SMALL_STATE(12)] = 166,
  [SMALL_STATE(13)] = 174,
  [SMALL_STATE(14)] = 187,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 213,
  [SMALL_STATE(17)] = 223,
  [SMALL_STATE(18)] = 233,
  [SMALL_STATE(19)] = 243,
  [SMALL_STATE(20)] = 253,
  [SMALL_STATE(21)] = 263,
  [SMALL_STATE(22)] = 273,
  [SMALL_STATE(23)] = 280,
  [SMALL_STATE(24)] = 287,
  [SMALL_STATE(25)] = 292,
  [SMALL_STATE(26)] = 299,
  [SMALL_STATE(27)] = 304,
  [SMALL_STATE(28)] = 309,
  [SMALL_STATE(29)] = 316,
  [SMALL_STATE(30)] = 321,
  [SMALL_STATE(31)] = 325,
  [SMALL_STATE(32)] = 329,
  [SMALL_STATE(33)] = 333,
  [SMALL_STATE(34)] = 337,
  [SMALL_STATE(35)] = 341,
  [SMALL_STATE(36)] = 345,
  [SMALL_STATE(37)] = 349,
  [SMALL_STATE(38)] = 353,
  [SMALL_STATE(39)] = 357,
  [SMALL_STATE(40)] = 361,
  [SMALL_STATE(41)] = 365,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_line, 2, 0, 5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_items, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_items, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_items_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_items_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_items_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_items_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dish_with_count, 1, 0, 6),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dish, 3, 0, 8),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dish_with_count, 2, 0, 7),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_item, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shopping_marker, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 6, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_starttag_line, 2, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_with_count, 1, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_line, 3, 0, 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_with_count, 2, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_persons_line, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [87] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_menu(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "menu",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
